### ISSUE TITLE
Numerics, handle `0.1 + 0.2 == 0.3`

### ISSUE THREAD

**Issue by Ayc0** [jviide/smort#4]
As in JS `0.1 + 0.2` is different than `0.3` due to how floats work, should the numeric logic be changed to check for `if (Math.abs(a - b) < Number.EPSILON)` after the case `if (a == b)`?

**Comment by jviide** [comment]
Thanks for bringing this up! Aren't floats wonderful? 😅

In this specific use case (a sorting function) I think we _probably_ should skip the epsilon check for the following reason:

```js
> const a = 0.29999999999999985;
> const b = 0.3;
> const c = 0.1 + 0.2;
>
> Math.abs(a - b) < Number.EPSILON;
true
> Math.abs(b - c) < Number.EPSILON;
true
> Math.abs(a - c) < Number.EPSILON;
false
```

I.e. we end up in a situation where we might have `a == b` and `b == c` be true, but `a == c` not be true. This breaks the [transitivity](https://en.wikipedia.org/wiki/Transitive_relation#Examples) of `==`, making the comparison function inconsistent. I tried this with a modified `numeric2` function that performs the epsilon check:

```js
> [a, b, c].sort(numeric2)
[ 0.2999999999999998, 0.3, 0.30000000000000004 ]
> [c, b, a].sort(numeric2)
[ 0.30000000000000004, 0.3, 0.2999999999999998 ]
> [a, c, b].sort(numeric2)
[ 0.2999999999999998, 0.30000000000000004, 0.3 ]
```

This may be a scenario that doesn't come up too often in practice, but I do think consistency is a really valuable property to keep (as far as possible) in a function such as `numeric` 🙂

**Comment by developit** [comment]
Also seems worth pointing out that any solution to this would break the following:

```js
[0.3, 0.3 + 4e-17].sort(numeric)
   // ^ incorrectly coerced to 0.3
```

**Comment by jviide** [comment]
I'll close this issue now :)
